### ISSUE TITLE
Hello！ Does this project contain additional  wlan.ko?

### ISSUE THREAD

**Issue by WooDwayToneTion** [imzf/ulysse#4]
I've merged  Qualcomm driver source code with the official kernel source code.   After compling and replaceing boot.img , it  still  doesn't  work!    

My  phone  is  Redmi  NOTE  5A .

**Comment by imzf** [comment]
Sorry.  I haven't logged in to github for a long time.you can see https://github.com/bitrvmpd/msm-3.18/issues/25
