### ISSUE TITLE
Build Failed as WireGuard resource is not available

### ISSUE THREAD

**Issue by VioletLightning** [imzf/ulysse#5]
@imzf
in `ugg` branch, `fetch-latest-wireguard.sh` script in this [commit](https://github.com/imzf/ulysse/commit/0b601bfa05631bda8fe4da67a0de15b9051093dd) failed to download wireguard as resource is not available.

**Comment by imzf** [comment]
you can revert https://github.com/imzf/ulysse/commit/0b601bfa05631bda8fe4da67a0de15b9051093dd 
then see https://forum.xda-developers.com/android/development/wireguard-rom-integration-t3711635
